---
description: >-
  Downloads an artifact which was uploaded by workflow in the specified run attempt. This
  action mirrors the `actions/download-artifact` but additionally supports downloading an
  artifact from a specific `run-attempt`. 
# Inputs are intended to mirror the official action where applicable:
# https://github.com/actions/download-artifact#inputs
inputs:
  run-id:
    description: >-
      The workflow run ID where the desired artifact should be downloaded from.
    required: true
  run-attempt:
    description: The workflow run attempt for the given run ID.
    required: true
  name:
    description: >-
      The name of the artifact to download. Can use a regex to match multiple artifacts.
      (e.g. "my-artifact" or "/^my/")
    required: true
  path:
    description: Destination path. Defaults to `$GITHUB_WORKSPACE`.
    default: ${{ github.workspace }}
  merge-multiple:
    description: >-
      When multiple artifacts are matched, this changes the behavior of the destination
      directories. If `true`, the downloaded artifacts will be in the same directory
      specified by path. If `false`, the downloaded artifacts will be extracted
      into individual named directories within the specified path.
    default: "false"
  allow-fallback:
    description: >-
      Allow use of artifacts from previous run attempts if no artifact with the given
      `name` is present. If falling back is allowed and a workflow run is in progress
      users may be returned an artifact from a previous run attempt when this run attempt
      has not yet produced an updated artifact. To avoid this situation be sure to wait for
      the job which produces this artifact before running this action.
    default: "false"
  repository:
    description: >-
      The repository which ran the workflow containing the artifact.
    default: ${{ github.repository }}
  token:
    description: >-
      The GitHub token used to authenticate with the GitHub API. Need when attempting to
      access artifacts in a different repository.
    default: ${{ github.token }}
outputs:
  download-path:
    description: >-
      Absolute path where the artifact(s) were downloaded.
    value: ${{ steps.download.outputs.download-path }}
runs:
  using: composite
  steps:
    - name: Download artifact
      id: download
      shell: bash
      run: ${{ github.action_path }}/download.sh
      env:
        GH_REPO: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
        run_id: ${{ inputs.run-id }}
        run_attempt: ${{ inputs.run-attempt }}
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.path }}
        merge_multiple: ${{ inputs.merge-multiple }}
        allow_fallback: ${{ inputs.allow-fallback }}
