---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  test:
    name: Default inputs
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        if: ${{ github.run_attempt > 1 }}
        with:
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
          allow-fallback: true
      - name: Show downloaded run-attempt file
        if: ${{ github.run-attempt > 1 }}
        run: |
          cat run-attempt
      - name: Create run-attempt file
        run: |
          echo "${{ github.run_attempt }}" >run-attempt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: run-attempt
