---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  test:
    name: Test
    # These permissions are needed to:
    # - Checkout the repo
    # - Use `job-context`: https://github.com/beacon-biosignals/job-context#permissions
    # - Re-run a job from a workflow: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: beacon-biosignals/job-context@v1
        id: job
      - uses: ./
        id: download-run-attempt
        if: ${{ github.run_attempt > 1 }}
        with:
          name: my-artifact
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
          allow-fallback: true
      - name: Show downloaded run-attempt file
        if: ${{ github.run_attempt > 1 }}
        run: |
          [[ "$(cat run-attempt)" == "1" ]] || exit 1
      - name: Create run-attempt file
        if: ${{ steps.download-run-attempt.outcome == 'skipped' }}
        run: |
          echo -n "${{ github.run_attempt }}" >run-attempt
      - uses: actions/upload-artifact@v4
        if: ${{ steps.download-run-attempt.outcome == 'skipped' }}
        with:
          name: my-artifact
          path: run-attempt
      - name: Re-run job
        if: ${{ steps.download-run-attempt.outcome == 'skipped' }}
        run: |
          # https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run
          gh api -X POST "/repos/{owner}/{repo}/actions/jobs/${{ steps.job.outputs.id }}/rerun"
        env:
          GH_TOKEN: ${{ github.token }}
