---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  setup:
    name: Setup
    # These permissions are needed to:
    # - Re-run a job from a workflow: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run
    permissions:
      actions: write
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.workflow-run.outputs.run-id }}
    steps:
      - uses: beacon-biosignals/get-workflow-run@v1
        id: workflow-run
        with:
          workflow-file: upload.yaml
          commit-sha: ${{ github.event.pull_request.head.sha }}
      - uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-job
        with:
          run-id: ${{ steps.workflow-run.outputs.run-id }}
          job-name: All Attempts
      - uses: beacon-biosignals/wait-for-job@v1
        id: wait-for-job
        with:
          run-id: ${{ steps.workflow-run.outputs.run-id }}
          job-name: First Attempt
      - name: Re-run workflow
        run: |
          # https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-workflow
          gh api -X POST "/repos/{owner}/{repo}/actions/runs/${run_id:?}/rerun"
        env:
          GH_TOKEN: ${{ github.token }}
          run_id: ${{ steps.workflow-run.outputs.run-id }}

  test-each-attempt:
    name: Test Each Attempt
    needs: setup
    # These permissions are needed to:
    # - Checkout the repo
    # - Download an artifact
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run-attempt:
          - 1
          - 2
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: download-run-attempt
        with:
          name: upload-each-attempt
          run-id: ${{ needs.setup.output.run-id }}
          run-attempt: ${{ matrix.run-attempt }}
      - name: Show downloaded run-attempt file
        run: |
          [[ "$(jq -er .run_attempt <metadata.json)" -eq $run_attempt ]] || exit 1
        env:
          run_attempt: ${{ matrix.run-attempt }}

  test-first-attempt:
    name: Test First Attempt
    needs: setup
    # These permissions are needed to:
    # - Checkout the repo
    # - Download an artifact
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run-attempt:
          - 1
          - 2
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: download-run-attempt
        with:
          name: upload-each-attempt
          run-id: ${{ needs.setup.output.run-id }}
          run-attempt: ${{ matrix.run-attempt }}
          allow-fallback: true
      - name: Show downloaded run-attempt file
        run: |
          [[ "$(jq -er .run_attempt <metadata.json)" -eq 1 ]] || exit 1